Avoid boost build error
The error is:

> error: no template named 'conditional_t' in namespace 'std'; did you mean 'conditional'?

The template alias `conditional_t` is not available in C++11; it was added in C++14, as were most of the other type trait `*_t` versions. Therefore, C++14 is required to build the boost library.